"""subscription type edit

Revision ID: 7318e193acc0
Revises: d2d5e617c0b2
Create Date: 2025-03-31 10:50:06.851915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7318e193acc0'
down_revision = 'd2d5e617c0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_period', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.drop_column('subscription_period')

    # ### end Alembic commands ###
